Set contents write permission to GITHUB_TOKEN in order to attach binaries
Also minor, add comments to set +e set -e

diff --git a/.github/workflows/attach-binaries-to-release.yml b/.github/workflows/attach-binaries-to-release.yml
--- a/.github/workflows/attach-binaries-to-release.yml
+++ b/.github/workflows/attach-binaries-to-release.yml
@@ -42,7 +42,7 @@ jobs:
     name: Build & Publish Binaries
     timeout-minutes: 120
     permissions:
-      contents: read
+      contents: write
       actions: write
     strategy:
       matrix:
@@ -100,10 +100,10 @@ jobs:
         shell: bash
         id: check_archive
         run: |
-          set +e
+          set +e # By default github workflow terminates immediately on non-zero exit-code.
           gcloud_output=$(gcloud storage ls gs://mysten-walrus-binaries/site-builder-${{ steps.validate_tag_name.outputs.site-builder-tag }}-${{ env.os_type }} 2>&1)
           exit_code=$?
-          set -e
+          set -e # Reset default github workflow behavior.
           if [ ${exit_code} -eq 0 ]; then
             echo "exists=true" >> "$GITHUB_OUTPUT"
           elif [[ "${gcloud_output}" == *"URLs matched no objects"* ]]; then
