Update attach-binaries-to-release.yml - WIP

diff --git a/.github/workflows/attach-binaries-to-release.yml b/.github/workflows/attach-binaries-to-release.yml
--- a/.github/workflows/attach-binaries-to-release.yml
+++ b/.github/workflows/attach-binaries-to-release.yml
@@ -15,7 +15,6 @@ concurrency: ${{ github.workflow }}-${{ inputs.site-builder-tag || github.ref }}
 
 env:
   TAG_NAME: "${{ github.event.inputs.site-builder-tag || github.ref_name }}"
-  BINARY_LIST_FILE: "./binary-build-list.json"
   CARGO_TERM_COLOR: always
   # Disable incremental compilation.
   #
@@ -57,15 +56,16 @@ jobs:
     steps:
       - name: Clean up and validate tag name
         shell: bash
+        id: validate_tag_name
         run: |
           export site-builder-tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)
           [[ "${site-builder-tag}" == "main" ]] && echo "tag cannot be equals to 'main'" && exit 1
-          echo "site-builder-tag=${site-builder-tag}" >> $GITHUB_ENV
+          echo "site-builder-tag=${site-builder-tag}" >> $GITHUB_OUTPUT
 
-      - name: Check out ${{ env.site-builder-tag }}
+      - name: Check out ${{ steps.validate_tag_name.outputs.site-builder-tag }}
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
         with:
-          ref: ${{ env.site-builder-tag }}
+          ref: ${{ steps.validate_tag_name.outputs.site-builder-tag }}
 
       - name: Set up Cloud SDK
         uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a # pin@v2
@@ -96,30 +96,31 @@ jobs:
           export os_type="${system_os}-${arch}"
           echo "os_type=${system_os}-${arch}" >> $GITHUB_ENV
 
-      - name: Check if tar balls have been uploaded already
-        continue-on-error: true
+      - name: Check if site-builder binary has been uploaded already
+        shell: bash
+        id: check_archive
+        run: |
+          gcloud_output=$(gcloud storage ls gs://mysten-walrus-binaries/site-builder-${{ steps.validate_tag_name.outputs.site-builder-tag }}-${{ env.os_type }} 2>&1)
+          exit_code=$?
+          if [ ${exit_code} -eq 0 ]; then
+            echo "exists=true" >> "$GITHUB_OUTPUT"
+          elif [[ "${gcloud_output}" == *"URLs matched no objects"* ]]; then
+            echo "exists=false" >> "$GITHUB_OUTPUT"
+          else
+            echo "An unexpected error occurred checking for the binary:"
+            echo "${gcloud_output}"
+            exit 1
+          fi
+
+      - name: Download from archive, if it exists
+        if: ${{ steps.check_archive.outputs.exists == true }}
         shell: bash
         run: |
-          site-builder_tarball_exist=$(gcloud storage ls gs://mysten-walrus-releases | \
-            grep -w "site-builder-${{ env.site-builder-tag }}-${{ env.os_type }}.tgz" | \
-            head -n 1 || echo '')
-
-          echo "site-builder_tarball_exist=$site_builder_tarball_exist" >> $GITHUB_ENV
-
-      - name: Download archive, if it exists
-        if: ${{ env.site-builder_tarball_exist != '' }}
-        shell: bash
-        run: |
-          mkdir -p ${{ env.TMP_BUILD_DIR }}
-          gcloud storage cp gs://mysten-walrus-releases/site-builder-${{ env.site-builder-tag }}-${os_type}.tgz ./tmp/site-builder-${{ env.site-builder-tag }}-${os_type}.tgz
-          tar -xf ./tmp/site-builder-${{ env.site-builder-tag }}-${os_type}.tgz -C ${{ env.TMP_BUILD_DIR }}
-
-      - name: Install nexttest (Windows)
-        if: ${{ startsWith(matrix.os, 'windows') && env.site_builder_tarball_exist == '' }}
-        uses: taiki-e/install-action@cargo-hack # pin@cargo-hack
+          mkdir -p ./site-builder-binaries
+          gcloud storage cp gs://mysten-walrus-binaries/site-builder-${{ steps.validate_tag_name.outputs.site-builder-tag }}-${os_type} ./site-builder-binaries/site-builder-${{ steps.validate_tag_name.outputs.site-builder-tag }}-${os_type}
 
       - name: Remove unused apps (MacOS arm64)
-        if: ${{ matrix.os == 'macos-latest-xlarge' && env.site_builder_tarball_exist == '' }}
+        if: ${{ matrix.os == 'macos-latest-xlarge' && steps.check_archive.outputs.exists != true }}
         continue-on-error: true
         shell: bash
         run: |
@@ -132,38 +133,27 @@ jobs:
           df -h /
 
       - name: Cargo build for ${{ matrix.os }} platform
-        if: ${{ env.site_builder_tarball_exist == '' }}
+        if: ${{ steps.check_archive.outputs.exists != true }}
         shell: bash
         run: |
           [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --release
 
       - name: Rename and archive binaries for ${{ matrix.os }}
-        if: ${{ env.site_builder_tarball_exist == '' }}
+        if: ${{ steps.check_archive.outputs.exists != true }}
         shell: bash
         run: |
-          mkdir -p ${{ env.TMP_BUILD_DIR }}
-
-          [ ! -f ${{ env.BINARY_LIST_FILE }} ] && echo "${{ env.BINARY_LIST_FILE }} cannot be found" && exit 1
-          for binary in $(cat ${{ env.BINARY_LIST_FILE }} | jq -r '.release_binaries[]'); do
-            export binary=$(echo ${binary} | tr -d $'\r')
-            mv ./target/release/${binary}${{ env.extention }} ${{ env.TMP_BUILD_DIR }}/${binary}${{ env.extention }}
-          done
-
-          tar -cvzf ./tmp/site-builder-${{ env.site-builder-tag }}-${{ env.os_type }}.tgz -C ${{ env.TMP_BUILD_DIR }} .
-
-      - name: Remove temp staging files
-        shell: bash
-        run: rm -rf ${{ env.TMP_BUILD_DIR }}
+          mkdir -p ./site-builder-binaries
+          mv ./target/release/site-builder ./site-builder-binaries/site-builder-${{ steps.validate_tag_name.outputs.site-builder-tag }}-${{ env.os_type }}
 
       - name: List upload directory contents
         shell: bash
-        run: ls -al ./tmp
+        run: ls -al ./site-builder-binaries
 
       - name: Upload binaries for ${{ inputs.os }} platform to GCP
         uses: google-github-actions/upload-cloud-storage@7c6e11cb7291594c5dfe0bc1dd9cd905e31e600c # pin@v2
         with:
-          path: "./tmp"
-          destination: "mysten-walrus-releases"
+          path: "./site-builder-binaries"
+          destination: "mysten-walrus-binaries"
           parent: false
 
       - name: Upload release artifacts for ${{ matrix.os }} platform
@@ -172,11 +162,11 @@ jobs:
           name: walrus-binaries-${{ matrix.os }}
           if-no-files-found: error
           path: |
-            ./tmp/site-builder-${{ env.site-builder-tag }}-${{ env.os_type }}.tgz
+            ./tmp/site-builder-${{ steps.validate_tag_name.outputs.site-builder-tag }}-${{ env.os_type }}.tgz
 
-      - name: Attach artifacts to ${{ env.site-builder-tag }} release in GH
+      - name: Attach artifacts to ${{ steps.validate_tag_name.outputs.site-builder-tag }} release in GH
         uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # pin@v2.2.2
         with:
-          tag_name: ${{ env.site-builder-tag }}
+          tag_name: ${{ steps.validate_tag_name.outputs.site-builder-tag }}
           files: |
-            ./tmp/site-builder-${{ env.site-builder-tag }}-${{ env.os_type }}.tgz
+            ./tmp/site-builder-${{ steps.validate_tag_name.outputs.site-builder-tag }}-${{ env.os_type }}.tgz
